### ISSUE TITLE
[V2] Edge Agent - Docker commands logs are not available

### ISSUE THREAD

**Issue by jcorioland** [Azure/iot-edge-v1#608] opened 2018-05-22 06:40 UTC
- **V1 or V2 issue** 
V2

- **OS version and architecture used:** 
x86_x64 / Ubuntu / Windows

- **Version used:** <VERSION> 
V2 images

- **V2 Docker version and container type** 
Docker 18.* both Windows & Linux

# Description of the issue:

**Problem Statement:** When IoT Edge Agent executes Docker commands that fail, the log only states that the command was skipped. The partner would like for error information about the failure to be logged.

**Desired Experience:** IoT Edge Agent logs should contain error information when a Docker command fails.

# Console log of the issue:

2018-03-27 08:49:28.347 +00:00 [INF] - Plan execution ended for deployment 3
2018-03-27 08:49:33.392 +00:00 [INF] - Plan execution started for deployment 3
2018-03-27 08:49:33.392 +00:00 [INF] - Skipping command "Command Group: (
  [docker pull XXXX.azurecr.io/image-name]
  [docker create --name XXXX-import XXXX.azurecr.io/image-name]
  [docker start XXXX-import]
)" in deployment 3. Will retry in 48s
2018-03-27 08:49:33.392 +00:00 [INF] - Plan execution ended for deployment 3
2018-03-27 08:49:38.443 +00:00 [INF] - Plan execution started for deployment 3
2018-03-27 08:49:38.444 +00:00 [INF] - Skipping command "Command Group: (
  [docker pull XXXX.azurecr.io/image-name]
  [docker create --name XXXX-import XXXX.azurecr.io/image-name]
  [docker start XXXX-import]
)" in deployment 3. Will retry in 43s
2018-03-27 08:49:38.444 +00:00 [INF] - Plan execution ended for deployment 3
2018-03-27 08:49:43.494 +00:00 [INF] - Plan execution started for deployment 3
2018-03-27 08:49:43.494 +00:00 [INF] - Skipping command "Command Group: (
  [docker pull XXXX.azurecr.io/image-name]
  [docker create --name XXXX-import XXXX.azurecr.io/image-name]
  [docker start XXXX-import]
)" in deployment 3. Will retry in 38s
 
Would be useful to get more info about docker logs.​​​
To reproduce, just create a new Azure IoT Edge device deployment and enter a wrong Docker image name/tag.

**Comment by darobs** [comment] 2018-05-22 23:40
Thanks @jcorioland, 

I will log this in our backlog.

**Comment by darobs** [comment] 2018-05-29 18:15
Hello @jcorioland ,

As I was reviewing this issue,  I noticed the section of logs that is showing the commands skipped is indicating that these commands have been held off - we implement a holdoff retry mechanism for when starting a module fails - this is so that are not attempting to retry a "docker pull" every few seconds for a module that won't start. 

The original failure for the pull happened earlier in the logs, and they are logged, I confirmed this.  Does the partner want to see the failure reason for every time the commands are skipped?

**Comment by jcorioland** [comment] 2018-05-29 19:12
Hello @darobs, yes, this is the point actually. 
I remember we had to investigate a long time before being able to find it maybe hours before in the logs. 
I think it would be great to have at least an error code giving insights about why there is a continuous holdoff each time there is a new retry.

**Comment by darobs** [comment] 2018-05-29 20:56
Understood.  I'll update the PBI with that information.  Thanks.

**Comment by aribeironovaes** [comment] 2018-09-02 01:14
HI @jcorioland , 

Closing this issue here since it's v2 related. Check our latest version as well. Is you still see this issue (or if we haven't improve the logs), please open an issue there so we can track. 

Thanks a lot! 

Angelo Ribeiro.

**Closed by aribeironovaes** 2018-09-02 01:14 UTC
