### ISSUE TITLE
[V2] IoT Edge Hub fails to start on ARM device without IPv6

### ISSUE THREAD

**Issue by NikMeyer** [Azure/iot-edge-v1#481] opened 2018-01-19 10:22 UTC
We are trying to run the Azure IoT Edge V2 on an embedded ARM device without IPv6. The IoT Edge Agents starts and successfully connects to the IoT hub to download the module configuration and start the other modules. The IoT edge Hub then fails to start with the following exception:

`2018-01-19 09:38:42.754 +00:00 [INF] - Updated the edge hub store and forward configuration`
`2018-01-19 09:38:42.764 +00:00 [INF] - Initialized edge hub configuration`
`2018-01-19 09:38:42.766 +00:00 [INF] - Starting Http Server` 
`2018-01-19 09:38:44.692 +00:00 [FTL] - Unable to start`
`Kestrel.Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvException: Error -97 EAFNOSUPPORT address family not supported`

Full log: [EdgeHubLog.txt](https://github.com/Azure/iot-edge/files/1646094/EdgeHubLog.txt)

An [issue 1474](https://github.com/aspnet/KestrelHttpServer/issues/1474) on the Kestrel github indicates that Kestrel is trying to bind to an IPv6 address which is not supported by our host.

Edge Device OS Details:
`uname -a: Linux Debian_XXX 4.4.41-gda6bc34 #66 PREEMPT Tue Sep 19 11:52:21 CEST 2017 armv7l GNU/Linux`
`cat /proc/net/if_inet6: No such file or directory`

We have tried to configure different images hub images (microsoft/azureiotedge-hub:1.0-preview, 1.0.0-preview017-linux-arm32v7 ) with the same result. Is it possible to runt the IoT Edge without IPv6?

**Comment by aribeironovaes** [comment] 2018-01-19 18:22
Thanks a lot for reporting it @NikMeyer  

We will look into it and see how we can fix. 
We found some information on their github too that might help us solving it: 
https://github.com/aspnet/KestrelHttpServer/issues/1290

I will update this when we have a fix. 

Thanks again, 

Angelo Ribeiro.

**Comment by darobs** [comment] 2018-01-27 07:58
Hello @NikMeyer 

I was able to reproduce this issue, and I am working on how to get all of edgeHub's services to run without IPv6. 

It seems that .NET's dual mode socket is not very accommodating of systems that have no IPv6.  We think that most customers are going to want to have IPv6 available, so our default will be to support both.  To solve your problem, I'm considering making this a configurable option on the edgeHub - something like Kestral's "server.urls".  That means for your system you would need to have a custom environment variable in the edgeHub's createOptions.

Does that sound like an acceptable solution?

**Comment by NikMeyer** [comment] 2018-01-29 08:26
@darobs: Thanks. A configuration to disable the IPv6 binding would solve the issue of not being able to start on a non-IPv6 device. 

There is a second problem with the web server that will likely affect us: Examining the Docker configuration I can see that the server binds to port 443 of the host. One of our use cases involves running a web server inside our own IoT Edge Module to provide application specific diagnostics, configuration and web interfaces (e.g. when the edge is not yet connected to the cloud). Those web applications should use the standard port for HTTPs and this would result in a conflict with the internal server of the Edge Hub. I could also not find any information on what the Hub web server is exactly used for, if it is possible to rebind it to a different port, or completely disable it.

**Comment by darobs** [comment] 2018-01-29 17:49
We are creating an HTTPs service in order to invoke direct methods to modules on the IoT Edge.  Looks like we need to document what ports we're exposing and why.

Port assignment for service the IoT Edge hub exposes is being worked on right now.

**Comment by darobs** [comment] 2018-03-24 18:58
Hell @NikMeyer 

It looks like the dotnet core team addressed this issue, and it's been merged to master.  Fixing this in the corefx code was the best place to have this solution. However, I don't know when we'll see it in a release. (I tested this on 2.1 preview 1 but this doesn't yet have the fix.)  Will update again once we have confirmation.

If this is still an issue that needs to be resolved sooner, please let us know, we can still add a workaround in the application.

**Comment by darobs** [comment] 2018-04-19 23:35
Hello @NikMeyer 

Confirmed the .NET Core 2.1 preview 2 has the Socket issue addressed, and we moved to using the 2.1 preview.  You won't see these changes until the next release, however, so I'm marking this "fix checked in"

**Comment by aribeironovaes** [comment] 2018-08-30 23:50
Item fixed, so closing. If you find any problem, please open a new github issue on gateway v2 repo here: https://github.com/Azure/iotedge

**Closed by aribeironovaes** 2018-08-30 23:50 UTC
Labels: fix checked in
