### ISSUE TITLE
[v2] http proxy support for iotedgectl 

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/iot-edge-v1#465] opened 2018-01-10 06:01 UTC
iotedgectl doesn't take http proxy as command line option. Can http proxy support be added so that  v2  can be used from with in corporate environments? We are trying to migrate a v1 production application which was able to work over http proxy (inside a plant)

As per reply from Azure forums([1](https://feedback.azure.com/forums/907045-azure-iot-edge/suggestions/32576803-edgehub-and-http-proxy)), the December update of IoT Edge was to have the ability to speak over web sockets. But the still the proxy option is missing for `iotedgectl setup --help`

**Comment by avranju** [comment] 2018-01-10 19:39
`iotedgectl` itself doesn't directly connect to the internet. It does so by proxy (pun not intended) via Docker. From [Docker docs](https://docs.docker.com/engine/reference/commandline/cli/#environment-variables) it looks like one can configure web proxy settings via environment variables. It defers to the configuration possible via the Go programming language. You might want to try setting up the environment as documented [here](https://golang.org/pkg/net/http/#ProxyFromEnvironment) as system environment variables and then restart the Docker daemon and see if it works.

A simple test might be to setup the environment variables, restart docker and do a `docker pull` to see if it is able to pull images.

**Comment by kiranpradeep** [comment] 2018-01-11 06:20
Thanks for the reply. Docker pull succeeds and edgeAgent docker image is pulled correctly (initiated by iotedgectl). But it appears the edgeAgent then appears to connect to Azure IoT Hub via AMQP/AMQP_WebSockets which is failing (as edgeAgent is unaware of HTTP Proxy). Is there a way to specify the HTTP proxy option to edgeAgent module?

```
dk300@utx3115:~$ docker images
REPOSITORY                     TAG                 IMAGE ID            CREATED             SIZE
microsoft/azureiotedge-agent   1.0-preview         330fee8772e5        3 weeks ago         288 MB
hello-world                    latest              f2a91732366c        7 weeks ago         1.85 kB
dk300@utx3115:~$ docker ps -a
CONTAINER ID        IMAGE                                      COMMAND                  CREATED             STATUS                      PORTS               NAMES
1f000bb31b14        microsoft/azureiotedge-agent:1.0-preview   "/usr/bin/dotnet M..."   12 minutes ago      Up 6 minutes                                    edgeAgent
9ef9134670ef        hello-world                                "/hello"                 19 minutes ago      Exited (0) 18 minutes ago                       relaxed_nightingale
dk300@utx3115:~$ docker logs -f edgeAgent
2018-01-11 05:57:00.068 +00:00 [INF] - Starting module management agent.
2018-01-11 05:57:00.929 +00:00 [INF] - Version - 1.0.0-preview017.8307729 (ed4d58d0308db5d6cc2fbc5d5ece7de516683e58)
2018-01-11 05:57:00.930 +00:00 [INF] - 
        █████╗ ███████╗██╗   ██╗██████╗ ███████╗
       ██╔══██╗╚══███╔╝██║   ██║██╔══██╗██╔════╝
       ███████║  ███╔╝ ██║   ██║██████╔╝█████╗
       ██╔══██║ ███╔╝  ██║   ██║██╔══██╗██╔══╝
       ██║  ██║███████╗╚██████╔╝██║  ██║███████╗
       ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

 ██╗ ██████╗ ████████╗    ███████╗██████╗  ██████╗ ███████╗
 ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██╔════╝ ██╔════╝
 ██║██║   ██║   ██║       █████╗  ██║  ██║██║  ███╗█████╗
 ██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║██╔══╝
 ██║╚██████╔╝   ██║       ███████╗██████╔╝╚██████╔╝███████╗
 ╚═╝ ╚═════╝    ╚═╝       ╚══════╝╚═════╝  ╚═════╝ ╚══════╝

2018-01-11 05:57:01.323 +00:00 [INF] - Edge agent attempting to connect to IoT Hub via AMQP...
2018-01-11 05:57:01.987 +00:00 [INF] - Edge agent config backup created here - backup.json
2018-01-11 05:57:03.352 +00:00 [INF] - Created persistent store at /tmp/edgeAgent
2018-01-11 05:57:05.510 +00:00 [WRN] - Skipped updating reported properties because no saved reported properties exist yet.
2018-01-11 05:57:10.606 +00:00 [WRN] - Skipped updating reported properties because no saved reported properties exist yet.
2018-01-11 05:57:15.636 +00:00 [WRN] - Skipped updating reported properties because no saved reported properties exist yet.
2018-01-11 05:57:20.647 +00:00 [WRN] - Skipped updating reported properties because no saved reported properties exist yet.
2018-01-11 05:57:25.663 +00:00 [WRN] - Skipped updating reported properties because no saved reported properties exist yet.
2018-01-11 05:57:30.689 +00:00 [WRN] - Skipped updating reported properties because no saved reported properties exist yet.
2018-01-11 05:57:31.974 +00:00 [INF] - Edge agent attempting to connect to IoT Hub via AMQP over WebSocket...
2018-01-11 05:57:35.705 +00:00 [WRN] - Skipped updating reported properties because no saved reported properties exist yet.
2018-01-11 05:57:40.718 +00:00 [WRN] - Skipped updating reported properties because no saved reported properties exist yet.
2018-01-11 05:57:45.734 +00:00 [WRN] - Skipped updating reported properties because no saved reported properties exist yet.
2018-01-11 05:57:50.747 +00:00 [WRN] - Skipped updating reported properties because no saved reported properties exist yet.
2018-01-11 05:57:55.761 +00:00 [WRN] - Skipped updating reported properties because no saved reported properties exist yet.
2018-01-11 05:58:00.781 +00:00 [WRN] - Skipped updating reported properties because no saved reported properties exist yet.
2018-01-11 05:58:02.075 +00:00 [INF] - Edge agent attempting to connect to IoT Hub via AMQP...
2018-01-11 05:58:05.794 +00:00 [WRN] - Skipped updating reported properties because no saved reported properties exist yet.
2018-01-11 05:58:10.810 +00:00 [WRN] - Skipped updating reported properties because no saved reported properties exist yet.
2018-01-11 05:58:15.828 +00:00 [WRN] - Skipped updating reported properties because no saved reported properties exist yet.
2018-01-11 05:58:20.845 +00:00 [WRN] - Skipped updating reported properties because no saved reported properties exist yet.
2018-01-11 05:58:25.866 +00:00 [WRN] - Skipped updating reported properties because no saved reported properties exist yet.
```

**Comment by PtwHub** [comment] 2018-01-16 15:01
I'd like to emphasize the importance of proxy handling for iot-edge: most companies have proxies and many of them filter out everything but https:443 unless you get special permission. If you are one of a hundred products being tendered/considered/deployed in a large company, your chances of getting special permission are not great...

**Comment by avranju** [comment] 2018-01-18 00:03
Since the Edge Agent relies on the Azure IoT Hub Device SDK to connect to IoT Hub, I checked with the SDK team on proxy support for AMQP over Web Sockets which would be the option applicable here. It turns out that the Device SDK in turn depends on support for this to arrive in .NET Core which is being slated for their next release which is version 2.1. So that's where this train stops. With .NET Core 2.1, their road-map indicates that a preview release is slated for Q1 of this year and the GA release will be in Q2. Those timelines would roughly apply to Edge as well.

**Comment by PtwHub** [comment] 2018-01-18 08:06
Thank you for working this through. This is encouraging news. This really is a significant (show stopper) feature for real-world products, so please keep it in your test suite. We certainly will.

**Comment by kiranpradeep** [comment] 2018-01-18 12:24
Thanks for the reply and also for the timelines (really helpful). Should I leave this ticket open? I assume by Device SDK, you meant azure-iot-sdk-csharp project. If yes, I will also raise an issue in azure-iot-sdk-csharp Github issue page to know more about the particular .net core feature expected. This is surprising since azure-iot-sdk-c can use websockets over proxies and there are C# projects (not .net core though) using websockets over proxies([1](https://github.com/sta/websocket-sharp#connecting-through-the-http-proxy-server))

**Comment by Zuendelmeister** [comment] 2018-01-18 12:35
Hi all,

i can confirm that this is a very important issue here. 
So far this issue is about AMQP. I'd like to add MQTT to the discussion. Is proxy support for MQTT also possible with the new .NET Core version?
Thanks.

Best regards,
Zuendelmeister

**Comment by aribeironovaes** [comment] 2018-08-30 18:15
Closing this issue and moving to the v2 github: 
Here is the link: https://github.com/Azure/iotedge/issues/230

**Closed by aribeironovaes** 2018-08-30 18:15 UTC
Labels: enhancement
